const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function generateTestPDF() {
  const pdfFilePath = path.join(__dirname, 'test-agreement.pdf');
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  const writeStream = fs.createWriteStream(pdfFilePath);
  
  // Variables & Theme
  const primaryBlue = '#1D4ED8';
  const textDark = '#111827';
  const textMuted = '#6B7280';
  const borderLight = '#E5E7EB';
  const bgLight = '#F3F4F6';
  const pageWidth = 595.28;
  const contentWidth = pageWidth - 100;

  // Global Watermark & Footer Listener
  let pageNumber = 0;
  doc.on('pageAdded', () => {
    pageNumber++;
    doc.save();
    doc.rotate(-45, { origin: [doc.page.width/2, doc.page.height/2] });
    doc.fillColor('#F9FAFB').fontSize(60).font('Helvetica-Bold');
    doc.text('SNDNPRS OFFICIAL', doc.page.width/2 - 300, doc.page.height/2 - 20, { align: 'center', width: 600, lineBreak: false });
    doc.restore();

    // Footer
    const bottom = doc.page.height - 40;
    doc.strokeColor(borderLight).lineWidth(1).moveTo(50, bottom - 15).lineTo(doc.page.width - 50, bottom - 15).stroke();
    
    doc.fontSize(7).font('Helvetica-Bold').fillColor(primaryBlue)
       .text('This agreement was digitally generated by the Somali National Digital Notary & Property Registry System (SNDNPRS).', 50, bottom - 5, { lineBreak: false });
       
    doc.font('Helvetica').fontSize(7).fillColor(textMuted)
       .text('Scan the QR Code to verify authenticity.', 50, bottom + 5, { lineBreak: false });
    
    doc.text(`Page ${pageNumber}`, doc.page.width - 100, bottom, { align: 'right', width: 50, lineBreak: false });
  });

  doc.pipe(writeStream);

  // --- HEADER ---
  // Coat of Arms placeholder (Star)
  doc.save();
  doc.translate(doc.page.width/2, 60);
  doc.scale(0.8);
  doc.fillColor('#3B82F6');
  doc.path('M 0 -25 L 5.8 -7.5 L 23.7 -7.5 L 9.3 3.5 L 14.7 21.2 L 0 11.2 L -14.7 21.2 L -9.3 3.5 L -23.7 -7.5 L -5.8 -7.5 Z').fill();
  doc.restore();

  doc.moveDown(4);
  doc.fillColor(textDark).fontSize(10).font('Helvetica-Bold')
     .text('SOMALI NATIONAL DIGITAL NOTARY & PROPERTY REGISTRY SYSTEM (SNDNPRS)', 50, 95, { align: 'center', width: contentWidth });
     
  doc.fillColor(primaryBlue).fontSize(18).font('Helvetica-Bold')
     .text('OFFICIAL PROPERTY AGREEMENT', 50, 110, { align: 'center', width: contentWidth, characterSpacing: 1 });
     
  doc.fillColor(textMuted).fontSize(12).font('Helvetica-Bold')
     .text('SALE AGREEMENT', 50, 130, { align: 'center', width: contentWidth, characterSpacing: 2 });

  doc.strokeColor(primaryBlue).lineWidth(2).moveTo(50, 150).lineTo(doc.page.width - 50, 150).stroke();
  
  doc.fillColor(textDark).fontSize(9).font('Helvetica-Bold').text('Agreement Number: AGR-123456', 50, 160);
  doc.text(`Agreement Date: ${new Date().toLocaleDateString()}`, doc.page.width - 200, 160, { align: 'right', width: 150 });
  
  let curY = 185;

  // --- HELPER FUNCTIONS ---
  const drawSectionHeader = (title, yPos) => {
    doc.fillColor(bgLight).rect(50, yPos, contentWidth, 20).fill();
    doc.strokeColor(primaryBlue).lineWidth(1).rect(50, yPos, contentWidth, 20).stroke();
    doc.fillColor(primaryBlue).fontSize(10).font('Helvetica-Bold').text(title.toUpperCase(), 60, yPos + 6);
    return yPos + 25;
  };

  const drawTable = (startX, startY, rows, colWidths) => {
    let currentY = startY;
    const rowHeight = 18;
    
    rows.forEach((row, rowIndex) => {
      let currentX = startX;
      if (rowIndex === 0) {
        doc.fillColor(primaryBlue).rect(startX, currentY, colWidths.reduce((a,b)=>a+b,0), rowHeight).fill();
      }
      doc.strokeColor(borderLight).lineWidth(1).rect(startX, currentY, colWidths.reduce((a,b)=>a+b,0), rowHeight).stroke();
      
      row.forEach((cell, i) => {
        if (i > 0) doc.moveTo(currentX, currentY).lineTo(currentX, currentY + rowHeight).stroke();
        doc.fillColor(rowIndex === 0 ? 'white' : textDark)
           .font(rowIndex === 0 ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
        doc.text(String(cell || 'N/A'), currentX + 5, currentY + 5, { width: colWidths[i] - 10, align: 'left', height: rowHeight, lineBreak: false });
        currentX += colWidths[i];
      });
      currentY += rowHeight;
    });
    return currentY;
  };

  // 1. Property Information
  curY = drawSectionHeader('Property Information', curY);
  curY = drawTable(50, curY, [
    ['Field', 'Details', 'Field', 'Details'],
    ['Property ID', 'PROP-123', 'Property Number', 'PN-999'],
    ['Registry Reference', 'REF-ABC', 'Property Type', 'LAND'],
    ['District', 'HODAN', 'Address', 'Mogadishu'],
    ['Land Size', '500 sqm', 'Registration Date', '2023-01-01'],
    ['Current Certificate', 'CERT-123', '', '']
  ], [100, 147.5, 100, 147.5]);
  curY += 15;
  
  // 2. Sale Information
  curY = drawSectionHeader('Sale Information', curY);
  curY = drawTable(50, curY, [
    ['Transfer Number', 'Transfer Date', 'Payment Method', 'Sale Price', 'Currency'],
    ['TR-999', '2023-01-01', 'Bank Transfer', '50,000', 'USD']
  ], [100, 100, 100, 100, 95]);
  curY += 15;

  // 3. Contracting Parties
  curY = drawSectionHeader('Contracting Parties', curY);
  
  const drawPartyInfo = (x, y, title, data, isPlaceholder) => {
    doc.fillColor(bgLight).rect(x, y, 235, 140).fill();
    doc.strokeColor(borderLight).lineWidth(1).rect(x, y, 235, 140).stroke();
    
    // Photo Box
    doc.strokeColor(borderLight).rect(x + 10, y + 10, 80, 80).stroke();
    
    // Silhouette Drawing
    if (isPlaceholder) {
      doc.save();
      doc.translate(x + 50, y + 55);
      doc.fillColor('#D1D5DB');
      doc.circle(0, -15, 15).fill(); // Head
      doc.path('M -25 25 Q -25 5 0 5 Q 25 5 25 25 Z').fill(); // Shoulders
      doc.restore();
    }
    
    doc.fillColor(primaryBlue).fontSize(9).font('Helvetica-Bold').text(title, x + 10, y + 95, { width: 80, align: 'center' });
    
    // Details
    let dy = y + 15;
    const drawRow = (lbl, val) => {
      doc.fillColor(textMuted).fontSize(7).font('Helvetica-Bold').text(lbl, x + 100, dy);
      doc.fillColor(textDark).fontSize(8).font('Helvetica').text(val, x + 100, dy + 8);
      dy += 22;
    };
    
    drawRow('Full Name', data.name);
    drawRow('National ID', data.nid);
    drawRow('Phone & Email', `${data.phone} | ${data.email}`);
    drawRow('Address', data.address);
    drawRow('Signature Date', data.date);
  };
  
  drawPartyInfo(50, curY, 'SELLER', {
    name: 'John Doe', nid: 'NID-123', phone: '25261000', email: 'john@test.com', address: 'Hodan, Mogadishu', date: '2023-01-01'
  }, true);
  
  drawPartyInfo(310, curY, 'BUYER', {
    name: 'Jane Smith', nid: 'NID-456', phone: '25262000', email: 'jane@test.com', address: 'Waberi, Mogadishu', date: '2023-01-01'
  }, true);

  curY += 155;

  // 4. Terms & Conditions
  if (curY > doc.page.height - 200) {
    doc.addPage();
    curY = 60;
  }
  
  curY = drawSectionHeader('Terms & Conditions', curY);
  doc.fillColor(textDark).font('Helvetica').fontSize(8);
  const terms = [
    'Seller confirms they are the legal and rightful owner of the property and hold full authority to sell.',
    'Property is free from all disputes, encumbrances, mortgages, and legal claims.',
    'Buyer agrees to accept full ownership and responsibilities upon execution of this agreement.',
    'Both parties agree to abide by the property laws and regulations of the Federal Republic of Somalia.',
    'The digital signatures appended to this document are legally binding under Somali law.',
    'The Somali National Digital Notary & Property Registry System maintains the official ownership record.'
  ];
  terms.forEach((t, i) => {
    doc.text(`${i+1}. ${t}`, 55, curY);
    curY += 14;
  });
  curY += 10;
  
  if (curY > doc.page.height - 200) {
    doc.addPage();
    curY = 60;
  }

  // 5. Signature Section
  curY = drawSectionHeader('Official Signatures & Verification', curY);
  
  const drawSigBox = (x, y, title, name, date, stampText) => {
    doc.strokeColor(borderLight).lineWidth(1).rect(x, y, 160, 110).stroke();
    doc.fillColor(bgLight).rect(x+1, y+1, 158, 20).fill();
    doc.fillColor(primaryBlue).font('Helvetica-Bold').fontSize(8).text(title, x + 5, y + 6);
    
    // Fake Sig
    doc.fillColor(textMuted).font('Courier').fontSize(14).text('DIGITAL SIGNATURE', x+5, y+40);
    
    doc.fillColor(textDark).font('Helvetica-Bold').fontSize(8).text(name, x+5, y+80);
    doc.fillColor(textMuted).font('Helvetica').fontSize(7).text(`Date: ${date}`, x+5, y+92);
  };
  
  drawSigBox(50, curY, 'SELLER SIGNATURE', 'John Doe', '2023-01-01', '');
  drawSigBox(220, curY, 'BUYER SIGNATURE', 'Jane Smith', '2023-01-01', '');
  drawSigBox(390, curY, 'GOVERNMENT NOTARY', 'Notary Ali', '2023-01-02', '');
  
  curY += 125;
  
  // Fake QR Code
  doc.strokeColor(borderLight).rect(50, curY, 80, 80).stroke();
  doc.fillColor(primaryBlue).rect(55, curY + 5, 70, 70).fill();
  doc.fillColor(textDark).font('Helvetica-Bold').fontSize(8).text('Scan QR to verify', 140, curY + 30);
  doc.text('Agreement ID: AGR-123456', 140, curY + 45);

  doc.end();
  
  writeStream.on('finish', () => console.log('Done'));
}

generateTestPDF();
